# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/intellifix_dev
spring.datasource.username=fix_usr
spring.datasource.password=Intellifix@123
spring.jpa.hibernate.ddl-auto=none