# Database Connection Settings
spring.datasource.url=jdbc:postgresql://intellifix-uat.c9wk4omkk0j4.ap-southeast-2.rds.amazonaws.com:5432/intellifix
spring.datasource.username=postgres
spring.datasource.password=Intellifix2026
spring.jpa.hibernate.ddl-auto=none