# Database Connection Settings
spring.datasource.url=jdbc:postgresql://dpg-d6c057a4d50c73d0smkg-a.singapore-postgres.render.com:5432/intellifix_dev
spring.datasource.username=fix_usr
spring.datasource.password=O8oIW4r8ZLOnXt2P491RaCILcfIn8E90
spring.jpa.hibernate.ddl-auto=none