# Database Connection Settings
spring.datasource.url=jdbc:postgresql://fix_usr:O8oIW4r8ZLOnXt2P491RaCILcfIn8E90@dpg-d6c057a4d50c73d0smkg-a/intellifix_dev
spring.datasource.username=fix_usr
spring.datasource.password=O8oIW4r8ZLOnXt2P491RaCILcfIn8E90
spring.jpa.hibernate.ddl-auto=none