spring.application.name=orchestrator
server.servlet.context-path=/intellifix/orchestrator
server.port=8080
# spring.profiles.active will be picked up from SPRING_PROFILES_ACTIVE environment variable automatically
spring.profiles.active=uat

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Settings
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis Connection Settings
spring.data.redis.host=redis-18130.c264.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=18130
spring.data.redis.username=default
spring.data.redis.password=7oWzCuoMWOswvG2NXeuUvAEIzzv3n3Y8

# Redis Stream Settings
redis.simulation.stream.name=sim_stream
redis.simulation.client.stream.name=sim_client_stream
redis.simulation.broker.stream.name=sim_broker_stream
redis.simulation.consumer.group=sim_consumer
redis.simulation.client.consumer.group=sim_client_consumer
redis.simulation.broker.consumer.group=sim_broker_consumer
redis.status.stream.name=status_stream
redis.status.consumer.group=status_consumer
redis.health.stream.name=fix_health_stream
redis.health.consumer.group=health_consumer

# Logging Settings
logging.file.name=logs/intellifix-orchestrator.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# FIX Log message for AI Analysis
ai.analysis.comparison.message-types=D,8
